name: Wiki-Gateway
version: 0.00141
abstract: API for interaction with wikis
author: Bayle Shanks
license: perl
distribution_type: module
build_requires:
  Test::Unit: 0
requires:
  SOAP::Lite: 0
  XMLRPC::Lite: 0
  Date::Manip: 0
  LWP::Simple: 0
  XML::RSS: 0
  HTML::Form: 0
  LWP::UserAgent: 0
  HTTP::Cookies: 0
  SOAP::Lite: 0
no_index:
  directory:
    - t
    - inc
generated_by: Module::Install version 0.35
